Develop
trilogy-group/JTU-2K22-BestPractices pull request #10
Opened 2022-05-21 16:47 UTC by omkar-ti

2022-05-21 16:51 UTC, omkar-ti commented
- Removed `import *`
- Modified imports where only a single function was required
- Put the secret key in .env file, .env file is present in gitignore
- Added type hints and annotations wherever possible
- Replaced numerical HTTP status codes with provided enums

2022-05-23 07:26 UTC, Smith-TI commented
As requested by @kushal-ti I'm taking up this PR for a preliminary review before his final review

2022-05-23 07:27 UTC, Smith-TI commented
Nit: Use [Github Tasklist](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists) for a better UI for PRs with multiple tasks

2022-05-23 07:51 UTC, Smith-TI requested changes
Preliminary Review 1

2022-05-23 07:51 UTC, Smith-TI commented on manage.py
> +    runserver.DEFAULT_PORT = DEFAULT_PORT
`DEFAULT_PORT` doesn't exist on runserver

```suggestion
    runserver.default_port = DEFAULT_PORT
```

2022-05-23 07:51 UTC, Smith-TI commented on restapi/views.py
> +def sort_by_time_stamp(logs) -> list:
Can be moved to another file (since this is not a view, but a utility function)

2022-05-23 07:51 UTC, Smith-TI commented on restapi/views.py
> +def multi_threaded_reader(urls, num_threads) -> list:
Instead of fetching the URLs one by one, fetch them concurrently

2022-05-23 07:51 UTC, Smith-TI commented on restapi/views.py
> +def logProcessor(request) -> Response:
1. Rename the function
2. Add Logging to determine the time taken to process logs

2022-05-23 07:51 UTC, Smith-TI commented on restapi/serializers.py
> +    def create(self, validated_data) -> Expenses:
Add doctrings to describe what the function does

2022-05-29 08:38 UTC, omkar-ti commented
@Smith-TI I have tried doing the changes as suggested.

2022-06-06 05:24 UTC, closed without merging