Soumyadeep-best practices
trilogy-group/JTU-2K22-BestPractices pull request #13
Opened 2022-05-21 19:15 UTC by SoumyadeepTrilogy

2022-05-23 06:19 UTC, kushal-ti requested changes

2022-05-23 06:19 UTC, kushal-ti commented on restapi/views.py
> +
logging configuration should go into it's separate utility file as a reusable callable method or loggerfactory class

2022-05-23 06:19 UTC, kushal-ti commented on restapi/views.py
> +
django specifcally has even better ways to handle this, that you can look into, but from a general perspective, keep your logging configs separate from application logic

2022-05-23 06:19 UTC, kushal-ti commented on restapi/views.py
Use proper naming conventions for classes

2022-05-23 06:19 UTC, kushal-ti commented on restapi/views.py
> +        logger.info("logger function executed")
logger function executed ?

2022-05-23 06:19 UTC, kushal-ti commented on restapi/views.py
> +        logger.info("expenses function initiated")
logging could be a lot better. Try adding some contextual data and perhaps some info about time taken to execute a function

2022-05-23 06:19 UTC, kushal-ti commented on restapi/views.py
> +    logger.info("multithreadreader function initiated")
method can be optimized. Recall the section on performance and efficiency

2022-05-26 08:58 UTC, SoumyadeepTrilogy commented on restapi/views.py
Resolved!

2022-05-26 08:59 UTC, SoumyadeepTrilogy commented on restapi/views.py
> +
Resolved!

2022-05-26 09:14 UTC, SoumyadeepTrilogy commented on restapi/views.py
> +    logger.info("multithreadreader function initiated")
Done!

2022-05-26 09:25 UTC, SoumyadeepTrilogy commented on restapi/views.py
> +        logger.info("expenses function initiated")
Resolved it!

2022-06-06 05:24 UTC, closed without merging