Jtu 2k22 adityapurohit
trilogy-group/JTU-2K22-BestPractices pull request #15
Opened 2022-05-21 23:55 UTC by adityapurohit1771

2022-05-23 05:42 UTC, kushal-ti requested changes
Good attempt. Make some of the changes i've requested and i'll approve

2022-05-23 05:42 UTC, kushal-ti commented on .gitignore
> +restapi/__pycache__/
you can just use **/__pycache__/ to automatically add all pycache folders to .gitingore

2022-05-23 05:42 UTC, kushal-ti commented on restapi/views.py
> +EXECUTOR_TIMEOUT = 60
should go directly into the constants file instea

2022-05-23 05:42 UTC, kushal-ti commented on restapi/views.py
> +    logging.info(f"Deleting auth_token for {request.user.id}")
I'm not completely sure about this, but most likely, this won't log anything. python logging doesn't work like this, you need to call logging.basicConfig() at some point to configure a console logger. Also, it's preferable to use the getLogger method to get a separate logger instance, with custom attributes for logger name and default level than just using logging

2022-05-23 05:42 UTC, kushal-ti commented on restapi/views.py
> +    logging.info("Getting Balances")
add docstrings across the codebase

2022-05-23 05:42 UTC, kushal-ti commented on restapi/views.py
> +        logging.error("Failed to fetch data for log proccesing")
literally the first example i've seen so far where someone did exception handling properly, kudos

2022-05-23 05:42 UTC, kushal-ti commented on restapi/views.py
> +def multi_thread_reader(urls:list, num_threads:int)->list:
would be better to clump all log_processor related functions into a separate utility class than having them all in views.py

2022-05-23 05:42 UTC, kushal-ti commented on restapi/views.py
> +            key = f"{hours}:00-{hours}:15"
extra points for using f-strings :+1:

2022-05-23 05:42 UTC, kushal-ti commented on restapi/serializers.py
remove dead code from expense serializer

2022-05-23 08:29 UTC, adityapurohit1771 commented
> Good attempt. Make some of the changes i've requested and i'll approve

Updated with required Changes @kushal-ti

2022-05-24 06:56 UTC, kushal-ti commented
looks good

2022-05-24 06:56 UTC, closed without merging