Jtu 2k22 bhoomilgohel
trilogy-group/JTU-2K22-BestPractices pull request #16
Opened 2022-05-22 10:36 UTC by bhoomil-TI

2022-05-23 05:32 UTC, kushal-ti requested changes
Please make the requested changed

2022-05-23 05:32 UTC, kushal-ti commented on restapi/serializers.py
>          #     group = Groups.objects.get(pk=data['group'].id)
dead code should be removed

2022-05-23 05:32 UTC, kushal-ti commented on restapi/serializers.py
> +        try:
think about what you're doing here with this exception handling. 
This is the equivalent of swallowing an exception. Even if there is a validation error, you will log it and return the attrs to the caller, making them think that the data is valid when it's not.

Exception Handling is more than just logging the exception

2022-05-23 05:32 UTC, kushal-ti commented on restapi/views.py
>  from restapi.serializers import *
no wild card imports, also remove deadcode and unused imports

2022-05-23 05:32 UTC, kushal-ti commented on restapi/views.py
> +    logs = multiThreadedReader(
you changed the name of the method where it's defined but not where it's being called. This only happens when you change the name manually, instead of using the IDE to refactor something. Next time use F2 (VSCode) or shift+F6 (pycharm)

2022-05-23 05:32 UTC, kushal-ti commented on restapi/views.py
> +from restapi.custom_exception import UnauthorizedUserException
i don't see any logs or docstrings throughout the project

2022-05-23 05:32 UTC, kushal-ti commented on restapi/views.py
> +def multi_threaded_reader(urls, num_threads) -> list:
method can be optimised, recall the section on performance and efficiency

2022-05-23 05:32 UTC, kushal-ti commented on restapi/views.py
> +def logProcessor(request) -> Response:
use python naming conventions for method names

2022-05-23 05:32 UTC, kushal-ti commented on restapi/views.py
> +def logProcessor(request) -> Response:
Also use proper naming conventions for all the classes in the code

2022-05-23 05:32 UTC, kushal-ti commented on restapi/views.py
> +def transform(logs) -> list:
Would be better if all functions relevant to log_processor would be grouped together in a separate file rather than dumping it all in views.py

2022-05-23 07:31 UTC, bhoomil-TI commented
Thanks for the insights, I tried to make the relevant changes and updated my code. @kushal-ti

2022-05-24 06:55 UTC, kushal-ti commented
cool, closing this

2022-05-24 06:55 UTC, closed without merging