Follow Best Practices
trilogy-group/JTU-2K22-BestPractices pull request #18
Opened 2022-05-22 19:07 UTC by yogesh-ti

Made changes for the following
- Replaced hard coded numbers with constants
- Removed unused imports
- Removed * imports
- Changed function names
- Changed class names
- Created env configuration for secret keys
- Added logging
- Updated readme

2022-05-23 05:09 UTC, kushal-ti requested changes
Please make the suggested changes

2022-05-23 05:09 UTC, kushal-ti commented on README.md
> +If you don't know anything about django-rest-framework don't worry because I also don't. You don't have to run the project or make any changes that requires knowledge intimate knowledge of django-res
lol

2022-05-23 05:09 UTC, kushal-ti commented on restapi/models.py
> +DECIMAL_PLACES = 2
it's better to put all constants in their own constants.py file than defining constants at the top of each file

2022-05-23 05:09 UTC, kushal-ti commented on restapi/views.py
> +def multi_threaded_reader(urls, num_threads):
method can be optimised. Remember the section on performance and efficiency

2022-05-23 05:09 UTC, kushal-ti commented on restapi/views.py
>              user_balances = UserExpense.objects.filter(expense=expense)
feels like duplicate code, between this and the normalize function defined earlier

2022-05-23 05:09 UTC, kushal-ti commented on restapi/views.py
>      data = aggregate(cleaned)
all functions related to processing logs should be organised together, probably in a separate file instead of polluting views.py

2022-05-23 11:07 UTC, yogesh-ti commented on restapi/views.py
> +def multi_threaded_reader(urls, num_threads):
Done [here](https://github.com/trilogy-group/JTU-2K22-BestPractices/pull/18/commits/d462f0714c13d5f21c275e355afedd3189b33b82)

2022-05-23 11:07 UTC, yogesh-ti commented on restapi/views.py
>      data = aggregate(cleaned)
Done [here](https://github.com/trilogy-group/JTU-2K22-BestPractices/pull/18/commits/7c978fde60a475907d917e0aa7d4ad0fe2dcea95)

2022-05-23 11:08 UTC, yogesh-ti commented on restapi/views.py
>              user_balances = UserExpense.objects.filter(expense=expense)
Done [here](https://github.com/trilogy-group/JTU-2K22-BestPractices/pull/18/commits/94055c4415f3d6c977feb8121330d6354058bf0b)

2022-05-23 11:09 UTC, yogesh-ti commented
@kushal-ti made the requested improvements

2022-05-24 06:55 UTC, kushal-ti commented
looks good to me

2022-05-24 06:55 UTC, closed without merging