adding Environment Variables module
trilogy-group/JTU-2K22-BestPractices pull request #3
Opened 2022-05-19 22:07 UTC by rajkotiya1

2022-05-20 18:59 UTC, kushal-ti requested changes
Left some comments, please address them. Also, try to see if you can introduce some basic static typing/type annotations. Don't bother with complex types that are coming from django if you don't understand them, but basic types annotations like str, int, etc. can still be helpful

2022-05-20 18:59 UTC, kushal-ti commented on restapi/serializers.py
> +from logging import logger
It's usually considered a good practice to configure loggers with the necessary formatter and handlers in a separate locations, either a utility file or in case of django, directly in the settings.py file.

You can then just import those loggers where ever required (perhaps you can also implement a class that returns an instance of a logger, like a logger factory).

Think about what happens when you instantiate and configure a logger for each file separately. What if you want to change the format of logs or send logs to a file instead of to the console. You'll have to make those changes separately for each logger. Remember DRY.

2022-05-20 18:59 UTC, kushal-ti commented on restapi/serializers.py
> +        logger.info("expense is updated successfully")
I think this is a misleading log? The expense isn't actually updated until instance.save() is called on line 74.

2022-05-20 18:59 UTC, kushal-ti commented on restapi/serializers.py
> +        logger.info("an expense is creted")
Nitpick: Avoid typos in log statements

2022-05-20 18:59 UTC, kushal-ti commented on restapi/serializers.py
> +        logger.info("an expense is creted")
Additionally, this log itself tells me nothing. Expense was created by who? What users does the expense involve? etc. I'm ignoring this for now, since this is application specific, so i can understand that you couldn't have know this before hand, but keep it in mind going forward

2022-05-20 18:59 UTC, kushal-ti commented on restapi/serializers.py
> +        try:
Is this change really helpful? Think about what you're doing here. Earlier, if there was an exception while saving the instance, it would break the normal flow of execution and send an exception to the client. In your case, the exception is caught, it's logged and then the execution will proceed as if nothing happened and will try to return an instance object that actually wasn't saved. Even though an error happened and was logged, the caller will have no idea that something failed. This is almost like swallowing an exception.

2022-05-20 18:59 UTC, kushal-ti commented on restapi/views.py
>      return Response(response, status=200)
Don't hardcode HTTP response codes

2022-05-20 18:59 UTC, kushal-ti commented on restapi/views.py
> +    start = int(time.time() * 1000.0)
you're using this pattern for measuring time taken to execute a function repeatedly throughout the code. Can you think of design pattern which would allow you to add this extra functionality of measuring time elapsed to each function ?

2022-05-20 18:59 UTC, kushal-ti commented on restapi/views.py
> +        try:
Again, catching an exception and just logging it creates more problems than it solves. Your program execution will continue as if nothing happened. 
Exception handling is more than just catching and logging them

2022-05-20 18:59 UTC, kushal-ti commented on restapi/views.py
>  class user_view_set(ModelViewSet):
Follow python naming conventions for naming all classes

2022-05-20 18:59 UTC, kushal-ti commented on restapi/views.py
>  def logProcessor(request):
use python naming conventions for function names

2022-05-20 18:59 UTC, kushal-ti commented on restapi/views.py
>      logs = multiThreadedReader(urls=data['logFiles'], num_threads=data['parallelFileProcessingCount'])
Multithreaded reader can be optimized. Remember to use concurrency for I/O intensive workloads

2022-05-20 18:59 UTC, kushal-ti commented on restapi/views.py
>      logs = multiThreadedReader(urls=data['logFiles'], num_threads=data['parallelFileProcessingCount'])
Also use python naming conventions for naming functions

2022-05-21 06:16 UTC, kushal-ti requested changes
just a few nitpicks, otherwise looks good

2022-05-21 06:16 UTC, kushal-ti commented on cjapp/settings.py
> +class Logger_Factory(self):
It's fine if you go with this for now, but django specifically has in-built ways of handling log configuration. Do take a look at that https://docs.djangoproject.com/en/4.0/howto/logging/#logging-how-to

2022-05-21 06:16 UTC, kushal-ti commented on restapi/serializers.py
> +        logger.info("expense is updated successfully")
misleading log is still here

2022-05-21 06:16 UTC, kushal-ti commented on restapi/views.py
>  from restapi.serializers import *
don't use wildcard imports

2022-05-21 06:16 UTC, kushal-ti commented on restapi/views.py
> +def Calculate_time(fnc):
use snake_case for function names

2022-05-21 06:16 UTC, kushal-ti commented on restapi/views.py
> +    return Response(response, status=)env("HTTP_status_200")
rest_framework has a status object which has been imported here, use that instead. You can see it being used in multiple other places instead

2022-05-21 06:16 UTC, kushal-ti commented on restapi/views.py
> +class CATEGORY_VIEW_SET(ModelViewSet):
This is not the right naming convention. Look up TitleCase, that's the preferred naming convention for python classes

2022-05-21 06:16 UTC, kushal-ti commented on restapi/views.py
> +def multiThreadedReader(urls, num_threads)->list:
snake_case for function names

2022-05-23 05:46 UTC, kushal-ti reviewed
Naming conventions are still not being followed for classes.

2022-05-23 05:46 UTC, kushal-ti commented on restapi/models.py
> +class CATEGORY(models.Model):   #UPPER_SNAKE_CASE for class or application constants
Does this look like an application constant ?

2022-05-23 06:14 UTC, rajkotiya1 commented on restapi/models.py
> +class CATEGORY(models.Model):   #UPPER_SNAKE_CASE for class or application constants
I thought it used for class name or application constants

2022-05-24 06:49 UTC, kushal-ti commented
alright, closing this

2022-05-24 06:49 UTC, closed without merging