[WIP] [Refactor]: Implement best practises
trilogy-group/JTU-2K22-BestPractices pull request #4
Opened 2022-05-20 03:43 UTC by Smith-TI

List of changes:

- [ ] Add `.gitignore`
- [ ] Add `.env` and remove all sensitive data from the code
- [ ] Restructure folder structure to standard django app structure
- [ ] Remove hardcoded values
- [ ] Add/Improve comments and docstrings on functions
- [ ] Add setup instructions in Readme
- [ ] Add logs 
- [ ] Add exception handling
- [ ] Follow the DRY Principle

2022-05-23 06:23 UTC, kushal-ti commented on restapi/utils.py
> +def multiThreadedReader(urls) -> list:
nitpick: use proper naming conventions for method names

2022-05-23 06:28 UTC, kushal-ti requested changes
Good attempt. Really impressed by how extensively static typing was implemented.
fix some of the nitpicks and i'll approve

2022-05-23 06:28 UTC, kushal-ti commented on restapi/utils.py
> +def multiThreadedReader(urls) -> list:
nitpick: use proper naming conventions for function names

2022-05-23 06:28 UTC, kushal-ti commented on restapi/utils.py
> +def multiThreadedReader(urls) -> list:
This particular method can be optimized by using proper concurrency primitives

2022-05-23 06:28 UTC, kushal-ti commented on restapi/views.py
>  class category_view_set(ModelViewSet):
nitpick: Use proper naming conventions in naming classes

2022-05-23 06:28 UTC, kushal-ti commented on restapi/views.py
> +def logProcessor(request) -> Response:
nitpick: function name

2022-05-23 06:28 UTC, kushal-ti commented on restapi/views.py
> +    logging.info(
better to use a separate logger instance than the default logging module

2022-05-23 06:43 UTC, Smith-TI commented on restapi/utils.py
> +def multiThreadedReader(urls) -> list:
> nitpick: use proper naming conventions for function names
Renamed to `multi_threaded_url_reader`

2022-05-23 07:07 UTC, CapriciousRebel commented on restapi/utils.py
> +def multiThreadedReader(urls) -> list:
> This particular method can be optimized by using proper concurrency primitives

Replaced the `for loop` with `ThreadPoolExecutor` for concurrency and speed optimization

2022-05-23 07:08 UTC, Smith-TI commented on restapi/utils.py
> +def multiThreadedReader(urls) -> list:
> This particular method can be optimized by using proper concurrency primitives

Replaced the `for loop` with `ThreadPoolExecutor` for concurrency and speed optimization

2022-05-23 07:13 UTC, Smith-TI commented on restapi/views.py
>  class category_view_set(ModelViewSet):
Renamed viewsets to PascalCase

2022-05-23 07:15 UTC, Smith-TI commented on restapi/views.py
> +def logProcessor(request) -> Response:
Renamed `logProcessor` to `process_logs`

2022-05-23 07:20 UTC, Smith-TI commented on restapi/views.py
> +    logging.info(
Added a custom logger `logger.py`

2022-05-24 06:49 UTC, kushal-ti commented
looks good to me

2022-05-24 06:49 UTC, closed without merging