Refactor codebase to adopt best practices
trilogy-group/JTU-2K22-BestPractices pull request #5
Opened 2022-05-20 17:58 UTC by ArpitShuklaTI

2022-05-20 19:13 UTC, kushal-ti requested changes
Apart from the lack of logs, rest mostly looks good to me, just a few nit picks. Please make the requested changes

2022-05-20 19:13 UTC, kushal-ti commented on restapi/views.py
> +    READ_TIMEOUT = 60
This should go in either settings.py or a separate constants file.
Also, HTTP_READ_TIMEOUT is better name IMO.

2022-05-20 19:13 UTC, kushal-ti commented on restapi/views.py
>      def create(self, request, *args, **kwargs):
i don't see any logs anywhere throughout the project

2022-05-20 19:13 UTC, kushal-ti commented on restapi/models.py
>      description = models.CharField(max_length=200)
Get rid of magic values for max_length and max_digits. 
Also, the values for max_length seems arbitrarily 100 or 200. Try to use a consistent value

2022-05-20 19:13 UTC, kushal-ti commented on restapi/views.py
> -    logs = multiThreadedReader(urls=data['logFiles'], num_threads=data['parallelFileProcessingCount'])
All of the code pertaining to processing logs should probably go into it's own class or utility rather than polluting views.py

2022-05-21 03:36 UTC, ArpitShuklaTI commented on restapi/views.py
> +    READ_TIMEOUT = 60
Fixed it.

2022-05-21 03:37 UTC, ArpitShuklaTI commented on restapi/views.py
>      def create(self, request, *args, **kwargs):
Added logs in [this](https://github.com/trilogy-group/JTU-2K22-BestPractices/pull/5/commits/2e65d9de456cec146d6e3c84be8c0d45476cf842) commit.

2022-05-21 03:37 UTC, ArpitShuklaTI commented on restapi/models.py
>      description = models.CharField(max_length=200)
Created a new constants file to maintain such constants.

2022-05-21 03:38 UTC, ArpitShuklaTI commented on restapi/views.py
> -    logs = multiThreadedReader(urls=data['logFiles'], num_threads=data['parallelFileProcessingCount'])
Done!

2022-05-21 06:21 UTC, kushal-ti approved these changes
Look good. Logging should normally be a bit more extensive, but extra points for using F-strings in the logs :+1:

2022-05-21 06:22 UTC, kushal-ti commented
Everything looks good, i'll be closing the PR

2022-05-21 06:22 UTC, closed without merging