Refactored Code using Best Practices
trilogy-group/JTU-2K22-BestPractices pull request #7
Opened 2022-05-21 06:16 UTC by davidgargti20

Work Done

- Added GitIgnore File
- Added Env variables file
- Added constants file
- Used predefined status code
- Removed unused imports
- Refactored code
- Change hardcoded values to constants and env variables
- Corrected and uncommented validation
- Used Parallelism to improve performance
- Added static typing
- Added comments
- Added logs
- Added Tests
- Updated Requirements
- Reorganised code
- Reformatted code
- Updated Readme

2022-05-21 07:30 UTC, davidgargti20 commented
Accidentally my all commits are from my personal id as in my it was set default didn't noticed. Will avoid this in my future projects and tasks.

2022-05-23 07:02 UTC, kushal-ti requested changes

2022-05-23 07:02 UTC, kushal-ti commented on restapi/tests.py
> +class UserExpenseTestCase(TestCase):
You're making test cases without using mocks, every time you run these tests, you're gonna end up modifying the actual DB.

Moreover, you are testing in-built library methods instead of the functions that you defined. Those work, no need to test them

2022-05-23 07:02 UTC, kushal-ti commented on restapi/views.py
>  class group_view_set(ModelViewSet):
class naming conventions

2022-05-24 06:48 UTC, kushal-ti commented
looks good

2022-05-24 06:48 UTC, closed without merging