Best Practices
trilogy-group/JTU-2K22-BestPractices pull request #8
Opened 2022-05-21 06:32 UTC by Shivam-TI

The changes to be sorted out before reviewing:

- [ ] Update README
- [x] Follow standard naming conventions for classes and functions
- [x] Add .gitignore
- [x] Add .env
- [ ] Update requirements.txt
- [x] Remove hardcoded status codes
- [ ] Move hardcoded constants
- [x] Remove unused imports and import all
- [ ] Add static typing
- [ ] Add logging

2022-05-22 17:50 UTC, Shivam-TI commented
Hi @kushal-ti, this PR is ready to be reviewed.

2022-05-23 06:32 UTC, kushal-ti requested changes
Really good. just have one change. Also, static typing could be a bit more extensive, but this is fine too

2022-05-23 06:32 UTC, kushal-ti commented on restapi/utils.py
> +def multi_threaded_reader(urls, num_threads) -> list:
method can be optimized by using proper concurrency primitives

2022-05-23 07:51 UTC, Shivam-TI commented on restapi/utils.py
> +def multi_threaded_reader(urls, num_threads) -> list:
I have now changed the method to use ThreadPoolReader.

2022-05-24 06:57 UTC, closed without merging